routes/admin.php
<?php

use App\Http\Controllers\admin\WinController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'guest', 'namespace' => 'admin'], function () {
    Route::any('/', 'UserController@index')->name('admin_login');
    Route::post('main/checklogin', 'UserController@checklogin');
});



Route::group(['middleware' => 'auth:admin', 'namespace' => 'admin'], function () {

    // Dashboard
    Route::get('home', 'DashboardController@index')->name('admin_home');

    // User 
    // Route::resource('user', 'UsersController');
    Route::post('user/delete', 'UsersController@destroyAll');
    Route::post('state/delete', 'StateController@destroyAll');
    Route::post('city/delete', 'CityController@destroyAll');
    Route::post('role/delete', 'RoleController@destroyAll');
    Route::post('marchant/delete', 'UsersController@destroyAll');
    Route::get('user_list', 'UsersController@userlist');
    Route::get('enquiry/marchant', 'EnqueryController@marchantEnquiry');
    Route::get('enquiry/user', 'EnqueryController@userEnquiry');
    Route::post('offer/delete', 'OfferController@destroyAll');
    Route::post('product/delete', 'ProductController@destroyAll');
    Route::post('category/delete', 'CategoryController@destroyAll');
    Route::get('product/changeStatus', 'ProductController@changeproductStatus');
    Route::get('product/remove-image', 'ProductController@removeProductimage');

    // Master 
    Route::resources([
        'page'         => 'PagesController',
        'state'         => 'StateController',
        'city'         => 'CityController',
        'role'         => 'RoleController',
        'offer'         => 'OfferController',

        'marchant'      => 'UsersController',
        'product'      => 'ProductController',
        'category'      => 'CategoryController',
    ]);
    Route::get('marchant/status/{user}', 'UsersController@changestatus')->name('marchantchangestatus');
    Route::get('product/status/{user}', 'ProductController@changestatus')->name('productchangestatus');

    // page 
    Route::post('page/delete', 'PagesController@destroyAll');

    // setting 
    Route::resource('setting', 'SettingController');


    Route::get('logout', 'UserController@logout')->name('admin_logout');
    Route::get('general-setting', 'SettingController@edit')->name('general_setting');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/foo', function () {
    Artisan::call('passport:install');
    return 'clearede';
});
Route::get('/migrate', function(){
    \Artisan::call('migrate');
    return 'migrate';
});
Route::any('admin', function () {
    return false;
});


// Route::get('', 'HomeController@index')->name('home');
Route::group(['middleware' => 'guest', 'namespace' => 'admin'], function () {
    Route::any('/', 'UserController@index')->name('admin_login');
    Route::post('main/checklogin', 'UserController@checklogin');
});


Route::get('/passport', function() {
    $exitCode = Artisan::call('passport:install');
    return 'clearede';
});

        

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\Model\Category;
use Illuminate\Routing\Controller as BaseController;
use Intervention\Image\ImageManagerStatic as Image;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Str;
use Illuminate\Http\Request;

class CategoryController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lists = Category::with('cat')->withCount('product')->orderBy('id', 'desc')
        ->paginate(10);
        // dd($lists);
        // root category
        $cat = Category::get();
        
        $parentArr  = ['' => 'Select Category'];
        if (!$cat->isEmpty()) {
            foreach ($cat as $mcat) {
                $parentArr[$mcat->id] = $mcat->name;
            }
        }
      
        // set page and title ------------------
        $page  = 'category.add_category';
        $title = 'Add City';
        $data  = compact('page', 'title', 'lists', 'parentArr');

        // return data to view
        return view('admin.layout', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name'         => 'required',
        ];
        
        
        $request->validate($rules);
        $input = $request->all();
        $input['slug']    = $input['slug'] == '' ? Str::slug($input['name'], '-'):$input['slug'];
        // $input['password'] =  Hash::make($request->record['password']);  
        if($request->hasFile('image'))  { 
            
            $image       = $request->file('image');
            $filename    = uniqid() . $image->getClientOriginalName();
            $image_resize = Image::make($image->getRealPath());              
            // $image_resize->resize(750, 500);
            $image_resize->save(public_path('imgs/category/' .$filename));
            $input['image']   = $filename;
            
        }
        $obj = new Category($input);
        // $obj->images = json_encode($data);
         
        if ($obj->save()) {
            return redirect(url('admin/category'))->with('success', 'Success! New record has been added.');
        } else {
            return redirect(url('admin/category'))->with('danger', 'Error! Something going wrong.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    { 
        $edit     =  Category::find($id);
        $request->replace($edit->toArray());
        $request->flash();       

        $cat = Category::get();
        
        $parentArr  = ['' => 'Select Category'];
        if (!$cat->isEmpty()) {
            foreach ($cat as $mcat) {
                $parentArr[$mcat->id] = $mcat->name;
            }
        }           
        
        // set page and title ------------------
        $page = 'category.edit';
        $title = 'Edit Category';
        $data = compact('page', 'title', 'parentArr', 'id', 'edit');
        // return data to view

        return view('admin.layout', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $rules = [
            'name'         => 'required',
        ];
        
        
        $request->validate($rules);
        $input = $request->all();
        $input['slug']    = $input['slug'] == '' ? Str::slug($input['name'], '-'):$input['slug'];
        // $input['password'] =  Hash::make($request->record['password']);  
        if($request->hasFile('image'))  { 
            
            $image       = $request->file('image');
            $filename    = uniqid() . $image->getClientOriginalName();
            $image_resize = Image::make($image->getRealPath());              
            // $image_resize->resize(750, 500);
            $image_resize->save(public_path('imgs/category/' .$filename));
            $input['image']   = $filename;
            
        }

        $obj = Category::find($category->id);
        // $obj->save($input);
        if ($obj->update($input)) {
            return redirect(url('admin/category'))->with('success', 'Success! New record has been added.');
        } else {
            return redirect(url('admin/category'))->with('danger', 'Error! Something going wrong.');
        }

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $row)
    {
        $row->delete();
        return redirect()->back()->with('success', 'Success! Record has been deleted');
    }

    public function destroyAll(Request $request)
    {
        $ids = $request->sub_chk;
        // dd($ids);
        Category::whereIn('id', $ids)->delete();
        return redirect()->back()->with('success', 'Success! Select record(s) have been deleted');
    }
}

app/Http/Controllers/api/CategoryController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Model\Category;
use App\Model\Enquery;
use Illuminate\Http\Request;
use Validator;

use App\Model\Notification;
use App\Model\Product;
use App\Model\Shop;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{
	public function index(Request $request)
	{
		$lists = Category::latest()->get();

		if ($lists->isEmpty()) {
			$re = [
				'status' => false,
				'message'	=> 'No record(s) found.'
			];
		} else {
			$re = [
				'status' => true,
				'message'	=> $lists->count() . " records found.",
				'data'   => $lists
			];
		}

		return response()->json($re);
	}

	public function product(Category $id)
	{
		$category = $id;
		$lists = Product::latest()->with('shop')->where('category_id', $category->id)->get();

		$re = [
			'status' 	=> true,
			'data'   	=> $lists
		];

		return response()->json($re);
	}
}

resources/views/admin/inc/category/add_category.blade.php
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    @include('admin.common.sidebar')

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
       @include('admin.common.TopHeader')
        <!-- Begin Page Content -->
        <div class="container-fluid">
          <!-- Content Row -->
          @if (\Session::has('success'))
              <div class="alert alert-success toast-msg" style="color: green">
                  {!! \Session::get('success') !!}</li>
              </div>
          @endif

          @if (\Session::has('danger'))
              <div class="alert alert-danger toast-msg" style="color: red;">
                  {!! \Session::get('danger') !!}</li>
              </div>
          @endif
          <div class="row">
            <!-- Area Chart -->
            <div class="col-xl-12 col-lg-12">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Add Category</h6>
              <button class="btn btn-primary" data-toggle="collapse" data-target="#cat_box">+ Add</button>
                </div>

                 <!-- Card Body -->
                <div class="card-body collapse" id="cat_box">
                {!! Form::open(['method' => 'POST', 'action' => 'admin\CategoryController@store', 'class' => 'user', 'files'=>'true']) !!}
                      @include('admin.template._category_form')
                  <div class="text-right">
                    <input type="submit"class="btn btn-primary" value="Add Category"/>
                  </div>
                {!! Form::close() !!}
                </div>
              </div>
            </div>
            <div class="col-xs-12 col-lg-12">
          {{ Form::open(['url' => url(env('ADMIN_DIR').'/category/'),'files' => true]) }}
              <div class="card">
                <div class="card-header d-sm-flex align-items-center justify-content-between mb-4">
                  <h6 class="m-0 font-weight-bold text-primary">Category List</h6>
                  <button class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"  data-url="{{ url(env('ADMIN_DIR').'/category/delete') }}" id="delete_all">Delete</button>
                </div>
                <div class="card-body">
                 <table class="table table-bordered">
                   <thead class="thead-dark">
                     <tr>
                       <th>S No.</th>
                       <th>Image</th>
                       <th>Category</th>
                       <th>Parent</th>
                       <!-- <th>State Name</th> -->
                       <!-- <th>Action</th> -->
                     </tr>
                   </thead>
                   <tbody>
                    @php
                    $sn = $lists->firstItem();
                    @endphp
                    @foreach($lists as $list)
                       <tr class="bg-light">
                        <td>{{ $sn++ }}. | 
                            @if($list->product_count == '0')
                            <input type="checkbox" name="sub_chk[]" value="{{ $list->id }}" class="sub_chk" data-id="{{$list->id}}">
                            @else
                            Is Used
                            @endif
                        </td>
                        <td>
                          @if($list->image != '')
                          <img src="{{ url('imgs/category/'.$list->image) }}" alt="{{ $list->name }}" width="50">
                          @else
                          N/A
                          @endif
                        </td>
                         <td><a href="{{route('category.edit', $list->id) }}">
                         <i class="far fa-edit" aria-hidden="true"></i>   {{$list->name}}</a></td>
                         <td>{{ $list->cat ? $list->cat->name : 'N/A' }}</td>
                        
                       </tr>
                     @endforeach
                   </tbody>
                 </table>

              {{  $lists->links() }}
                </div>

              </div>
          {{ Form::close() }}
            </div>
          </div>
         </div>
        <!-- /.container-fluid -->
      </div>
      <!-- End of Main Content -->
    </div>
    <!-- End of Content Wrapper -->

  </div>

resources/views/admin/inc/category/edit.blade.php
<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
    @include('admin.common.sidebar')

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">
       @include('admin.common.TopHeader')

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Category</h1>
            <a href="{{ url('admin/category') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> View Category</a>
          </div>

          <!-- Content Row -->

          <div class="row">
            <!-- Area Chart -->
            <div class="col-xl-12 col-lg-12">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Category Description</h6>
                </div>

                 <!-- Card Body -->
                <div class="card-body">
                  {!! Form::open(['method' => 'PUT', 'route'=>array('category.update', $edit['id']), 'class' => 'user', 'files'=>'true']) !!}
                      @include('admin.template._category_form')
                  <div class="text-right">
                    <input type="submit"class="btn btn-primary" value="Edit Category"/>
                  </div>
                {{ Form::close() }}
                </div>
              </div>
            </div>
          </div>
         </div>
        <!-- /.container-fluid -->
      </div>
      <!-- End of Main Content -->
    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->